name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/dnfield/flutter_svg
issue_tracker: https://github.com/dnfield/flutter_svg/issues
version: 2.0.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path_drawing: ^1.0.1
  vector_graphics: ^1.0.0
  vector_graphics_codec: ^1.0.0
  vector_graphics_compiler: ^1.0.0
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.1
  test: ^1.21.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.4.0-34.1.pre"

# dependency_overrides:
#   vector_graphics:
#     path: ../vector_graphics/packages/vector_graphics
#   vector_graphics_codec:
#     path: ../vector_graphics/packages/vector_graphics_codec
#   vector_graphics_compiler:
#     path: ../vector_graphics/packages/vector_graphics_compiler
