name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/flutter_svg
version: 0.14.1

dependencies:
  path_drawing: ^0.4.1
  xml: ^3.3.1
  vector_math: ^2.0.4
  meta: ^1.1.2
  http: ^0.12.0+2
  universal_io: ^0.8.4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.0.0
  path: ^1.5.1
  test: ^1.4.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.9-pre.94 <2.0.0"

## For developing features that require new functionality in engine:
# dependency_overrides:
#  sky_engine:
#    path: /Users/dnfield/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine
#  sky_services:
#    path: /Users/dnfield/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_services
