name: flutter_svg
description: An SVG rendering and widget library for Flutter.
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/flutter_svg
version: 0.2.0

dependencies:
  path_drawing: ^0.2.3
  xml: ^3.0.0
  vector_math: ^2.0.4
  meta: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.2.3
  path: ^1.5.1
  test: ^0.12.34
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/
    - assets/w3samples/
    - assets/deborah_ufw/
    - assets/simple/
    - assets/wikimedia/
    - assets/android_vd/

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.4.5-pre.69 <2.0.0"
