name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/dnfield/flutter_svg
issue_tracker: https://github.com/dnfield/flutter_svg/issues
version: 1.1.4

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path_drawing: ^1.0.1
  vector_math: ^2.1.2

  xml: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.1
  test: ^1.21.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.11.0-0.1.pre"

## For developing features that require new functionality in engine:
# dependency_overrides:
#  sky_engine:
#    path: /Users/dnfield/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine
#  sky_services:
#    path: /Users/dnfield/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_services
