name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/dnfield/flutter_svg/tree/master/packages/flutter_svg
issue_tracker: https://github.com/dnfield/flutter_svg/issues
version: 2.0.7

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.7
  vector_graphics_codec: ^1.1.7
  vector_graphics_compiler: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.19.0-0 <4.0.0'
  flutter: ">=3.7.0-0"

# dependency_overrides:
#   vector_graphics:
#     path: ../vector_graphics/packages/vector_graphics
#   vector_graphics_codec:
#     path: ../vector_graphics/packages/vector_graphics_codec
#   vector_graphics_compiler:
#     path: ../vector_graphics/packages/vector_graphics_compiler
